# Book title
title: "My Project Book"

# Name of the author
author: "Gopika Kumar"

# Theme settings (optional)
theme:
  name: "sphinx_book_theme"

# Path to markdown files
notebooks:
  - "notebooks/*.ipynb"
